<?php

namespace App\Actions\Agents;

use App\Billing\Exceptions\PlanLimitExceeded;
use App\Events\Domain\AgentCreated;
use App\Models\Agent;
use App\Models\Team;
use App\Provisioning\PoolAllocator;

/**
 * The single entry point for "make a new agent."
 *
 * Two paths:
 * - BYOK: empty draft, user pastes their own Voiceflow credentials in
 *   onboarding step 2, then UpdateAgentCredentials health-checks + activates.
 * - Managed (Phase J + K): allocates a pre-created Voiceflow project from
 *   the `voiceflow_project_pool` table, stamps the agent, marks active
 *   immediately. The user never sees Voiceflow.
 *
 * Why a pool? Earlier design cloned environments inside one master
 * Voiceflow project per tenant. Voiceflow docs (researched 2026-06-03)
 * confirm two blockers: 10-env hard cap per project across all tiers
 * AND shared KB/integrations/analytics across environments in a project.
 * That meant clone-per-tenant capped at 10 customers + leaked data
 * between them. The pool sidesteps both — each customer gets a
 * separately-created Voiceflow project (real isolation) at the cost
 * of operator pre-provisioning.
 */
class CreateAgent
{
    /**
     * @param  array<string, mixed>  $attributes  Optional initial creds (BYOK only).
     */
    public function execute(Team $team, string $name, array $attributes = []): Agent
    {
        // Plan limit guard. Throws BEFORE we touch the DB so we never leave
        // a half-created agent if the team hit their cap. The global
        // exception handler maps this to 403 for JSON and a flash-redirect
        // for web — see bootstrap/app.php.
        $plan = $team->planObject();
        $existing = $team->agents()->count();
        if ($existing >= $plan->maxAgents()) {
            throw new PlanLimitExceeded(
                resource: 'agents',
                limit: $plan->maxAgents(),
                plan: $plan,
            );
        }

        $effectiveName = $name !== '' ? $name : $this->defaultName($team);

        // Engine selection. 'native' (the Flowstack-owned runtime) needs no
        // external provisioning — no Voiceflow pool, no project: the agent
        // is live the moment the row exists. Anything else falls into the
        // legacy Voiceflow paths (pool-managed or BYOK).
        $agent = match (true) {
            config('runtime.default_mode') === 'native' => $this->createNative($team, $effectiveName),
            (bool) config('services.voiceflow.managed.enabled') => $this->createManaged($team, $effectiveName),
            default => $this->createByok($team, $effectiveName, $attributes),
        };

        event(new AgentCreated($agent));

        // If this is the team's first agent, make it current so the next page
        // load doesn't bounce back through OnboardingState::NeedsAgent.
        if (! $team->current_agent_id) {
            $team->forceFill(['current_agent_id' => $agent->id])->save();
        }

        return $agent->refresh();
    }

    /**
     * BYOK path: empty draft, user pastes credentials in onboarding step 2.
     *
     * @param  array<string, mixed>  $attributes
     */
    protected function createByok(Team $team, string $name, array $attributes): Agent
    {
        return $team->agents()->create([
            'name' => $name,
            'mode' => Agent::MODE_BYOK,
            // slug + webhook_secret auto-generated by Agent::booted().
            'voiceflow_api_key' => $attributes['voiceflow_api_key'] ?? null,
            'voiceflow_project_id' => $attributes['voiceflow_project_id'] ?? null,
            'voiceflow_environment' => $attributes['voiceflow_environment'] ?? 'main',
            'voiceflow_workspace_api_key' => $attributes['voiceflow_workspace_api_key'] ?? null,
            'status' => Agent::STATUS_DRAFT,
        ]);
    }

    /**
     * Managed path: allocate the next available pre-created Voiceflow
     * project from the pool, stamp this agent with that project's keys.
     *
     * Allocation failure (PoolExhausted — operator hasn't refilled) leaves
     * the draft agent row deleted so we don't accumulate half-provisioned
     * rows. The user sees a 503 from the global exception handler.
     */
    protected function createManaged(Team $team, string $name): Agent
    {
        // Create the agent shell first so the pool entry has something to
        // FK to. On allocation failure we delete the row in the catch.
        $agent = $team->agents()->create([
            'name' => $name,
            'mode' => Agent::MODE_MANAGED,
            'status' => Agent::STATUS_DRAFT,
        ]);

        try {
            $entry = app(PoolAllocator::class)->allocate($agent);
        } catch (\Throwable $e) {
            $agent->delete();
            throw $e;
        }

        $agent->forceFill([
            'voiceflow_api_key' => $entry->voiceflow_api_key,
            'voiceflow_project_id' => $entry->voiceflow_project_id,
            'voiceflow_environment' => $entry->voiceflow_environment ?: 'main',
            'voiceflow_workspace_api_key' => $entry->voiceflow_workspace_api_key,
            // Active immediately — the project + key were validated when
            // the operator added them to the pool. No health check.
            'status' => Agent::STATUS_ACTIVE,
            'last_health_check_at' => now(),
            'last_health_ok' => true,
        ])->save();

        return $agent;
    }

    /**
     * Native path: the Flowstack runtime serves this agent directly —
     * active immediately, zero external provisioning. Health depends only
     * on ANTHROPIC_API_KEY / OPENAI_API_KEY being present (checked by
     * AgentRuntime::health, surfaced on the agent page).
     */
    protected function createNative(Team $team, string $name): Agent
    {
        /** @var Agent $agent */
        $agent = $team->agents()->create([
            'name' => $name,
            'mode' => Agent::MODE_MANAGED, // user never touches credentials
            'runtime_mode' => Agent::RUNTIME_NATIVE,
            'status' => Agent::STATUS_ACTIVE,
            'last_health_check_at' => now(),
            'last_health_ok' => true,
        ]);

        return $agent;
    }

    protected function defaultName(Team $team): string
    {
        $existing = $team->agents()->count();

        return $existing === 0 ? 'Default agent' : 'Agent '.($existing + 1);
    }
}
