<?php

namespace App\Actions\Agents;

use App\Events\Domain\AgentCreated;
use App\Models\Agent;
use App\Models\Team;

/**
 * The single entry point for "make a new agent."
 *
 * Used by the onboarding wizard step 1, the agent CRUD page, and any future
 * API. Returns a draft Agent — credentials get filled in later via
 * UpdateAgentCredentials, then the agent activates on a passing health check.
 *
 * Why an action class rather than a method on the model: this is the layer
 * where business rules go (only one agent per team on a free plan, default
 * name based on existing agents, fires creation events). Keeping it out of
 * the model means the model stays a thin data container.
 */
class CreateAgent
{
    /**
     * @param  array<string, mixed>  $attributes  Optional initial creds — usually empty (wizard fills them in step 2).
     */
    public function execute(Team $team, string $name, array $attributes = []): Agent
    {
        $agent = $team->agents()->create([
            'name' => $name !== '' ? $name : $this->defaultName($team),
            // slug + webhook_secret auto-generated by Agent::booted().
            'voiceflow_api_key' => $attributes['voiceflow_api_key'] ?? null,
            'voiceflow_project_id' => $attributes['voiceflow_project_id'] ?? null,
            'voiceflow_environment' => $attributes['voiceflow_environment'] ?? 'main',
            'voiceflow_workspace_api_key' => $attributes['voiceflow_workspace_api_key'] ?? null,
            'status' => Agent::STATUS_DRAFT,
        ]);

        event(new AgentCreated($agent));

        // If this is the team's first agent, make it current so the next page
        // load doesn't bounce back through OnboardingState::NeedsAgent.
        if (! $team->current_agent_id) {
            $team->forceFill(['current_agent_id' => $agent->id])->save();
        }

        return $agent->refresh();
    }

    protected function defaultName(Team $team): string
    {
        $existing = $team->agents()->count();

        return $existing === 0 ? 'Default agent' : 'Agent '.($existing + 1);
    }
}
