<?php

namespace App\Actions\Agents;

use App\Billing\Exceptions\PlanLimitExceeded;
use App\Events\Domain\AgentCreated;
use App\Models\Agent;
use App\Models\Team;
use App\Services\VoiceflowService;
use RuntimeException;

/**
 * The single entry point for "make a new agent."
 *
 * Used by the onboarding wizard step 1, the agent CRUD page, and any future
 * API. Returns a draft Agent — credentials get filled in later via
 * UpdateAgentCredentials, then the agent activates on a passing health check.
 *
 * Phase J: when managed mode is enabled, CreateAgent clones the master
 * project's template environment into a fresh per-tenant environment via
 * the Voiceflow Project API. The user never sees Voiceflow. The agent
 * activates immediately (no credential paste step, no separate health check).
 *
 * Why an action class rather than a method on the model: this is the layer
 * where business rules go (only one agent per team on a free plan, default
 * name based on existing agents, fires creation events). Keeping it out of
 * the model means the model stays a thin data container.
 */
class CreateAgent
{
    /**
     * @param  array<string, mixed>  $attributes  Optional initial creds — usually empty (wizard fills them in step 2).
     */
    public function execute(Team $team, string $name, array $attributes = []): Agent
    {
        // Plan limit guard. Throws BEFORE we touch the DB so we never leave
        // a half-created agent if the team hit their cap. The global
        // exception handler maps this to 403 for JSON and a flash-redirect
        // for web — see bootstrap/app.php.
        $plan = $team->planObject();
        $existing = $team->agents()->count();
        if ($existing >= $plan->maxAgents()) {
            throw new PlanLimitExceeded(
                resource: 'agents',
                limit: $plan->maxAgents(),
                plan: $plan,
            );
        }

        $effectiveName = $name !== '' ? $name : $this->defaultName($team);

        $agent = config('services.voiceflow.managed.enabled')
            ? $this->createManaged($team, $effectiveName)
            : $this->createByok($team, $effectiveName, $attributes);

        event(new AgentCreated($agent));

        // If this is the team's first agent, make it current so the next page
        // load doesn't bounce back through OnboardingState::NeedsAgent.
        if (! $team->current_agent_id) {
            $team->forceFill(['current_agent_id' => $agent->id])->save();
        }

        return $agent->refresh();
    }

    /**
     * BYOK path: empty draft, user pastes credentials in onboarding step 2.
     *
     * @param  array<string, mixed>  $attributes
     */
    protected function createByok(Team $team, string $name, array $attributes): Agent
    {
        return $team->agents()->create([
            'name' => $name,
            'mode' => Agent::MODE_BYOK,
            // slug + webhook_secret auto-generated by Agent::booted().
            'voiceflow_api_key' => $attributes['voiceflow_api_key'] ?? null,
            'voiceflow_project_id' => $attributes['voiceflow_project_id'] ?? null,
            'voiceflow_environment' => $attributes['voiceflow_environment'] ?? 'main',
            'voiceflow_workspace_api_key' => $attributes['voiceflow_workspace_api_key'] ?? null,
            'status' => Agent::STATUS_DRAFT,
        ]);
    }

    /**
     * Managed path: ask Voiceflow to clone the template environment, store
     * the resulting env id, mark active immediately. The agent is usable
     * the moment this returns — no second wizard step.
     *
     * Failures here (Voiceflow rejects auth, template env not found, network
     * down) propagate up so the wizard can surface a real error rather than
     * landing the user on a half-created agent.
     */
    protected function createManaged(Team $team, string $name): Agent
    {
        $masterProjectId = config('services.voiceflow.managed.master_project_id');
        $templateEnvId = config('services.voiceflow.managed.template_environment_id');

        if (empty($masterProjectId) || empty($templateEnvId)) {
            throw new RuntimeException(
                'Managed mode is enabled but VOICEFLOW_MASTER_PROJECT_ID / VOICEFLOW_TEMPLATE_ENVIRONMENT_ID are unset.'
            );
        }

        // Hit Voiceflow BEFORE the DB write so a clone failure doesn't
        // leave us with an orphaned local row. Using a fresh service
        // instance (not the request-scoped one) so we don't accidentally
        // authenticate as a tenant that hasn't been created yet.
        $service = new VoiceflowService();
        $envId = $service->cloneEnvironment(
            masterProjectId: $masterProjectId,
            name: $team->name.' — '.$name,
            sourceEnvironmentId: $templateEnvId,
        );

        return $team->agents()->create([
            'name' => $name,
            'mode' => Agent::MODE_MANAGED,
            // Only the env id is per-tenant. Auth + project_id come from
            // .env via VoiceflowService::forAgent.
            'voiceflow_api_key' => null,
            'voiceflow_project_id' => null,
            'voiceflow_environment' => $envId,
            'voiceflow_workspace_api_key' => null,
            // Active immediately — Voiceflow already proved the env exists
            // by returning a valid clone id. No second-step health check.
            'status' => Agent::STATUS_ACTIVE,
            'last_health_check_at' => now(),
            'last_health_ok' => true,
        ]);
    }

    protected function defaultName(Team $team): string
    {
        $existing = $team->agents()->count();

        return $existing === 0 ? 'Default agent' : 'Agent '.($existing + 1);
    }
}
