#!/usr/bin/env bash
# Hermes Dashboard — auto-generated cross-session visualization.
# Writes docs/hermes/dashboard.md aggregating recent sessions (any type)
# into Mermaid timelines, summary tables, and trend lines.
# Run after a session, or whenever you want a fresh overview.
# No LLM, no scans — pure aggregation of session notes already on disk.

set -uo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

OUT="docs/hermes/dashboard.md"
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Gather all session notes — any TYPE prefix
mapfile -t notes < <(ls -t docs/hermes/{FLEET,DOCS,AUDIT,UPDATE,SYSTEM,LIFECYCLE,OBSIDIAN,FLOWCHARTS}-*.md 2>/dev/null)

extract() {
  local file=$1 field=$2
  grep -E "^${field}:" "$file" 2>/dev/null | head -1 | sed "s/^${field}:[[:space:]]*//" | tr -d '"'
}

# ── Header ────────────────────────────────────────────────────────────────────
{
  echo "---"
  echo "type: dashboard"
  echo "tags: [hermes, dashboard]"
  echo "generated: $TS"
  echo "---"
  echo ""
  echo "# Hermes Dashboard"
  echo ""
  echo "Auto-generated by \`composer hermes-dashboard\`. Regenerate after each session, or whenever you want a fresh overview."
  echo ""
  echo "**Last generated:** \`$TS\` · **Sessions on file:** ${#notes[@]}"
  echo ""

  # ── Recent sessions timeline (Mermaid) ──────────────────────────────────────
  echo "## Recent sessions"
  echo ""

  if [[ ${#notes[@]} -eq 0 ]]; then
    echo "_No session notes yet. Invoke any of /hermes-fleet, /hermes-docs, /hermes-audit, /hermes-update, /hermes-system, or /hermes-lifecycle to seed the first one._"
  else
    echo '```mermaid'
    echo 'timeline'
    echo '    title Recent sessions (newest 10)'

    # Group last 10 by date
    declare -A date_to_entries
    for f in "${notes[@]:0:10}"; do
      base=$(basename "$f" .md)
      type=$(echo "$base" | cut -d- -f1)
      date=$(extract "$f" "date")
      overall=$(extract "$f" "overall")
      [[ -z "$overall" ]] && overall=$(extract "$f" "final_overall")
      [[ -z "$overall" ]] && overall="—"
      key="${date:-unknown}"
      entry="${type} ${overall}"
      if [[ -n "${date_to_entries[$key]:-}" ]]; then
        date_to_entries[$key]="${date_to_entries[$key]}|${entry}"
      else
        date_to_entries[$key]="$entry"
      fi
    done

    # Render in date order (newest first → reverse for Mermaid which reads top-down chronologically)
    for date in $(echo "${!date_to_entries[@]}" | tr ' ' '\n' | sort); do
      echo "    $date"
      IFS='|' read -ra entries <<< "${date_to_entries[$date]}"
      for e in "${entries[@]}"; do
        echo "        : $e"
      done
    done

    echo '```'
    echo ""
  fi

  # ── Verdict tally by type ───────────────────────────────────────────────────
  echo "## Verdict tally"
  echo ""
  echo "| Type | PASS | WARN | FAIL | Total |"
  echo "|---|---|---|---|---|"

  for type in FLEET DOCS AUDIT UPDATE SYSTEM LIFECYCLE; do
    p=0; w=0; fail=0; total=0
    for f in docs/hermes/${type}-*.md; do
      [[ -f "$f" ]] || continue
      total=$((total + 1))
      overall=$(extract "$f" "overall")
      [[ -z "$overall" ]] && overall=$(extract "$f" "final_overall")
      case "$overall" in
        PASS) p=$((p + 1)) ;;
        WARN) w=$((w + 1)) ;;
        FAIL) fail=$((fail + 1)) ;;
      esac
    done
    [[ $total -gt 0 ]] && echo "| $type | $p | $w | $fail | $total |"
  done

  # ── Lifecycle trend (Mermaid graph if 2+ lifecycle runs) ─────────────────────
  mapfile -t lifecycles < <(ls -t docs/hermes/LIFECYCLE-*.md 2>/dev/null)
  if [[ ${#lifecycles[@]} -ge 2 ]]; then
    echo ""
    echo "## Lifecycle trend"
    echo ""
    echo "Verdict progression across the most recent ${#lifecycles[@]} lifecycle runs (oldest → newest):"
    echo ""
    echo '```mermaid'
    echo 'graph LR'

    # Reverse to chronological order
    for ((i=${#lifecycles[@]}-1; i>=0; i--)); do
      f="${lifecycles[i]}"
      base=$(basename "$f" .md)
      ts_short=$(echo "$base" | sed 's/LIFECYCLE-//')
      overall=$(extract "$f" "overall")
      node_id="L$i"
      label="\"$ts_short\\n$overall\""
      echo "    $node_id[$label]"
      if [[ $i -lt $((${#lifecycles[@]}-1)) ]]; then
        prev_id="L$((i+1))"
        echo "    $prev_id --> $node_id"
      fi
    done

    echo '```'
  fi

  # ── Session links table ────────────────────────────────────────────────────
  echo ""
  echo "## Session links"
  echo ""
  echo "| When | Type | Verdict | Note |"
  echo "|---|---|---|---|"
  for f in "${notes[@]:0:20}"; do
    base=$(basename "$f" .md)
    type=$(echo "$base" | cut -d- -f1)
    date=$(extract "$f" "date")
    overall=$(extract "$f" "overall")
    [[ -z "$overall" ]] && overall=$(extract "$f" "final_overall")
    [[ -z "$overall" ]] && overall="—"
    rel="${f#docs/hermes/}"
    rel_nomd="${rel%.md}"
    echo "| $date | $type | $overall | [[$rel_nomd]] |"
  done

  # ── Current snapshot ───────────────────────────────────────────────────────
  echo ""
  echo "## Current snapshot"
  echo ""
  echo "(From the latest \`composer hermes-status\` aggregation of on-disk findings JSON. Re-run for fresh data.)"
  echo ""
  echo "| Collector | Overall | Headline |"
  echo "|---|---|---|"

  if [[ -f data/hermes_findings.json ]]; then
    o=$(python3 -c "import json; d=json.load(open('data/hermes_findings.json')); print(d['overall'])" 2>/dev/null)
    p=$(python3 -c "import json; d=json.load(open('data/hermes_findings.json')); print(d['pass'])" 2>/dev/null)
    fl=$(python3 -c "import json; d=json.load(open('data/hermes_findings.json')); print(d['fail'])" 2>/dev/null)
    wr=$(python3 -c "import json; d=json.load(open('data/hermes_findings.json')); print(d['warn'])" 2>/dev/null)
    echo "| Watchdog | $o | $p PASS / $fl FAIL / $wr WARN |"
  fi
  if [[ -f data/agents/audit-sentinel/findings.json ]]; then
    o=$(python3 -c "import json; d=json.load(open('data/agents/audit-sentinel/findings.json')); print(d['overall'])" 2>/dev/null)
    c=$(python3 -c "import json; d=json.load(open('data/agents/audit-sentinel/findings.json')); print(d['critical'])" 2>/dev/null)
    h=$(python3 -c "import json; d=json.load(open('data/agents/audit-sentinel/findings.json')); print(d['high'])" 2>/dev/null)
    m=$(python3 -c "import json; d=json.load(open('data/agents/audit-sentinel/findings.json')); print(d['medium'])" 2>/dev/null)
    echo "| Audit | $o | $c CRITICAL / $h HIGH / $m MEDIUM |"
  fi
  if [[ -f data/agents/update-inspector/findings.json ]]; then
    o=$(python3 -c "import json; d=json.load(open('data/agents/update-inspector/findings.json')); print(d['overall'])" 2>/dev/null)
    pt=$(python3 -c "import json; d=json.load(open('data/agents/update-inspector/findings.json')); print(d['php_total'])" 2>/dev/null)
    jt=$(python3 -c "import json; d=json.load(open('data/agents/update-inspector/findings.json')); print(d['js_total'])" 2>/dev/null)
    echo "| Update | $o | PHP $pt / JS $jt outdated |"
  fi
  if [[ -f data/agents/system-check/findings.json ]]; then
    o=$(python3 -c "import json; d=json.load(open('data/agents/system-check/findings.json')); print(d['overall'])" 2>/dev/null)
    p=$(python3 -c "import json; d=json.load(open('data/agents/system-check/findings.json')); print(d['pass'])" 2>/dev/null)
    fl=$(python3 -c "import json; d=json.load(open('data/agents/system-check/findings.json')); print(d['fail'])" 2>/dev/null)
    wr=$(python3 -c "import json; d=json.load(open('data/agents/system-check/findings.json')); print(d['warn'])" 2>/dev/null)
    echo "| System | $o | $p PASS / $wr WARN / $fl FAIL |"
  fi

  echo ""
  echo "---"
  echo ""
  echo "_Regenerate this dashboard anytime: \`composer hermes-dashboard\`. Auto-regenerated by the end of every \`/hermes-lifecycle\` run._"
} > "$OUT"

echo "Dashboard written: $OUT"
