#!/usr/bin/env python3
"""
hermes_metrics.py — does the audit system actually move the needle?

Mines the git history (git IS the ledger) for direction-aware quality KPIs at
daily snapshots, charts the trajectory, and FLAGS REGRESSIONS (a KPI moving the
wrong way). Writes docs/hermes/effectiveness.md — the "is Hermes working?"
report. Periodic by design (see the 2026-06-14 learning-cadence decision): run
it at milestones, not on every commit.

KPIs (with their "good" direction):
  - phpstan baseline  (suppressed issues)        ↓ lower is better — debt paid down
  - debt density      (baseline / app php files) ↓ lower is better — debt per file
  - test files        (tests/**/*Test.php)        ↑ higher is better — coverage
  - docs              (docs/**/*.md)               ↑ higher is better

A "regression" is the latest snapshot moving against a KPI's good direction
(tests-down is only flagged if app code did NOT also shrink — i.e. a real loss,
not a deliberate removal).

Usage: python3 scripts/hermes_metrics.py   (writes the report + prints a summary)
"""
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(REPO)


def git(*a):
    return subprocess.run(["git", *a], capture_output=True, text=True).stdout


def count_lines(blob, pattern):
    return sum(1 for ln in blob.splitlines() if pattern in ln)


# Daily snapshots: the last commit of each calendar day.
rows = [ln.split("|") for ln in git("log", "--reverse", "--pretty=%h|%ad", "--date=short").splitlines() if "|" in ln]
last_of_day = {}
for sha, date in rows:
    last_of_day[date] = sha  # later commit on the same date wins

snaps = []
for date in sorted(last_of_day):
    sha = last_of_day[date]
    tree = git("ls-tree", "-r", "--name-only", sha)
    baseline = git("show", f"{sha}:phpstan-baseline.neon")
    base = count_lines(baseline, "message:")
    tests = sum(1 for f in tree.splitlines() if f.startswith("tests/") and f.endswith("Test.php"))
    docs = sum(1 for f in tree.splitlines() if f.startswith("docs/") and f.endswith(".md"))
    php = sum(1 for f in tree.splitlines() if f.startswith("app/") and f.endswith(".php"))
    density = round(base / php, 2) if php else 0.0
    snaps.append({"date": date, "base": base, "tests": tests, "docs": docs, "php": php, "density": density})

if len(snaps) < 2:
    print("hermes_metrics: not enough history")
    sys.exit(0)

first, last = snaps[0], snaps[-1]
# pick the snapshot where phpstan first appears (baseline > 0) for an honest delta
base_start = next((s for s in snaps if s["base"] > 0), first)


def pct(a, b):
    return f"{(b - a) / a * 100:+.0f}%" if a else "n/a"


# ── regression check: latest vs previous ───────────────────────────────────
prev, cur = snaps[-2], snaps[-1]
regressions = []
if cur["base"] > prev["base"]:
    regressions.append(f"phpstan baseline grew {prev['base']}→{cur['base']} (+{cur['base']-prev['base']} suppressed issues)")
if cur["density"] > prev["density"]:
    regressions.append(f"debt density rose {prev['density']}→{cur['density']} (more suppressed issues per file)")
if cur["tests"] < prev["tests"] and cur["php"] >= prev["php"]:
    regressions.append(f"test files dropped {prev['tests']}→{cur['tests']} while app code did NOT shrink — coverage loss")
if cur["docs"] < prev["docs"]:
    regressions.append(f"docs dropped {prev['docs']}→{cur['docs']}")


def chart(title, key, hint):
    labels = ", ".join(f'"{s["date"][5:]}"' for s in snaps)  # MM-DD
    vals = [s[key] for s in snaps]
    ymax = max(vals) + max(1, int(max(vals) * 0.1))
    series = ", ".join(str(v) for v in vals)
    return (f"```mermaid\nxychart-beta\n"
            f'    title "{title}  ({hint})"\n'
            f"    x-axis [{labels}]\n"
            f'    y-axis "{key}" 0 --> {ymax}\n'
            f"    line [{series}]\n```")


L = []
def w(s=""):
    L.append(s)

w("---")
w("type: ops")
w("tags: [hermes, metrics, effectiveness]")
w("---")
w()
w("# Hermes — effectiveness")
w()
w("> Auto-generated by `scripts/hermes_metrics.py` (`composer hermes-metrics`). Does the audit")
w("> system actually improve the codebase? This mines the git history for direction-aware")
w("> quality KPIs and flags regressions. Periodic, not per-run (see the 2026-06-14 decision).")
w()
w("## Strategy — what 'improvement' means")
w()
w("| KPI | Source | Good direction | A win looks like |")
w("|---|---|---|---|")
w("| PHPStan baseline | `phpstan-baseline.neon` | **↓** | suppressed-debt shrinks as you fix it |")
w("| Debt density | baseline ÷ `app/*.php` | **↓** | **debt falls even while the code grows** — the real signal |")
w("| Test files | `tests/**/*Test.php` | **↑** | coverage grows with features |")
w("| Docs | `docs/**/*.md` | **↑** | the doc-coverage gate keeps it climbing |")
w()
w("The headline test is **debt density**: if suppressed issues per file fall while the")
w("codebase grows, the gates are net-positive — you're adding code *and* paying down debt.")
w()
w(f"## Headline ({base_start['date']} → {last['date']})")
w()
w("| KPI | Start | Now | Δ |")
w("|---|---|---|---|")
w(f"| PHPStan baseline | {base_start['base']} | {last['base']} | **{pct(base_start['base'], last['base'])}** |")
w(f"| Debt density | {base_start['density']} | {last['density']} | **{pct(base_start['density'], last['density'])}** |")
w(f"| Test files | {first['tests']} | {last['tests']} | {pct(first['tests'], last['tests'])} |")
w(f"| Docs | {first['docs']} | {last['docs']} | {pct(first['docs'], last['docs'])} |")
w(f"| App PHP files | {first['php']} | {last['php']} | {pct(first['php'], last['php'])} |")
w()
w("## Charts")
w()
w(chart("PHPStan baseline — suppressed issues", "base", "down = better"))
w()
w(chart("Debt density — suppressed issues per app file", "density", "down = better"))
w()
w(chart("Test files", "tests", "up = better"))
w()
w(chart("Docs", "docs", "up = better"))
w()
w("## Regression check (latest vs previous snapshot)")
w()
if regressions:
    w("⚠️ **Regressions detected:**")
    for r in regressions:
        w(f"- {r}")
else:
    w("✅ No regressions — no KPI moved against its good direction in the latest snapshot.")
w()
w("## Data")
w()
w("| date | baseline | density | tests | docs | app php |")
w("|---|---|---|---|---|---|")
for s in snaps:
    w(f"| {s['date']} | {s['base']} | {s['density']} | {s['tests']} | {s['docs']} | {s['php']} |")
w()

os.makedirs("docs/hermes", exist_ok=True)
with open("docs/hermes/effectiveness.md", "w") as fh:
    fh.write("\n".join(L) + "\n")

# console summary
print(f"Hermes effectiveness ({base_start['date']} → {last['date']}):")
print(f"  PHPStan baseline : {base_start['base']} → {last['base']}  ({pct(base_start['base'], last['base'])})  [down=better]")
print(f"  Debt density     : {base_start['density']} → {last['density']}  ({pct(base_start['density'], last['density'])})  [down=better]")
print(f"  Test files       : {first['tests']} → {last['tests']}  ({pct(first['tests'], last['tests'])})")
print(f"  Docs             : {first['docs']} → {last['docs']}  ({pct(first['docs'], last['docs'])})")
if regressions:
    print("  ⚠️ regressions:")
    for r in regressions:
        print(f"    - {r}")
else:
    print("  ✅ no regressions in the latest snapshot")
print("  report → docs/hermes/effectiveness.md")
sys.exit(0)
