#!/usr/bin/env python3
"""
hermes_learn.py — the learning loop (Increment 6), deterministic half.

PERIODIC + PROPOSES-ONLY (see docs/hermes/decisions/2026-06-14-learning-is-
periodic-not-automated.md). Run at milestones, not per-run. It:

  1. snapshots the current findings graph into a history ledger
     (data/hermes_history.jsonl) — so per-check trends accumulate at YOUR cadence;
  2. mines that ledger + the verdict log + git for signals:
       - escaped defects → which manifest nodes lack a guarding granular check
         (learn from misses — the strongest signal even on the first run)
       - untested subsystems
       - flaky / repeat-failing checks (needs ≥3 ledger snapshots)
  3. writes REVIEWABLE proposals to data/hermes_learn_proposals.md.

It NEVER mutates the manifest. The /hermes-learn Claude session reflects on the
proposals (validates each against the code) and applies them as a human-reviewed
manifest diff. Deterministic facts here; judgement + the edit there.

Usage: python3 scripts/hermes_learn.py   (composer hermes-learn)
"""
import json
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(REPO)


def git(*a):
    return subprocess.run(["git", *a], capture_output=True, text=True).stdout


with open("docs/hermes/manifest.json") as fh:
    M = json.load(fh)
nodes = M["subsystems"]
checkdefs = M.get("checks", {})

# ── 1. snapshot the current findings graph into the on-demand ledger ────────
LEDGER = "data/hermes_history.jsonl"
history = []
if os.path.exists(LEDGER):
    history = [json.loads(ln) for ln in open(LEDGER) if ln.strip()]

if os.path.exists("data/hermes_findings.json"):
    with open("data/hermes_findings.json") as fh:
        d = json.load(fh)
    snap = {
        "ts": d.get("ts"),
        "overall": d.get("overall"),
        "checks": {f["check"]: f["status"] for f in d.get("findings", [])},
    }
    if not history or history[-1].get("ts") != snap["ts"]:
        os.makedirs("data", exist_ok=True)
        with open(LEDGER, "a") as fh:
            fh.write(json.dumps(snap) + "\n")
        history.append(snap)

# ── 2. verdict history from the rolling session log ─────────────────────────
verdicts = []
sess = "data/logs/hermes_session.log"
if os.path.exists(sess):
    for ln in open(sess):
        m = re.match(r"^(\S+)\s+(PASS|WARN|FAIL)\s+(\d+)/(\d+)/(\d+)", ln.strip())
        if m:
            verdicts.append(m.group(2))

# ── 3. escaped defects → nodes that lack a guarding granular check ──────────
FIX = re.compile(r"(?i)^\s*(fix|hotfix|bugfix|patch)\b|^\s*fix\(")
AUDIT = re.compile(r"(?i)\baudit\b|\bsurfaced\b|\bhermes\b")

commits, cur = [], None
for ln in git("log", "--reverse", "--name-only", "--pretty=format:@@@|%h|%s").splitlines():
    if ln.startswith("@@@|"):
        if cur:
            commits.append(cur)
        _, sha, subj = ln.split("|", 2)
        cur = {"sha": sha, "subj": subj, "files": []}
    elif ln.strip() and cur is not None:
        cur["files"].append(ln.strip())
if cur:
    commits.append(cur)


def node_of(path):
    cands = [k for k in nodes if path.startswith(k + "/")]
    return max(cands, key=len) if cands else None


def has_granular(k):
    return any(ch in checkdefs for ch in nodes[k].get("checks", []))


esc_by_node = {}
for c in commits:
    prod = any(f.startswith("app/") or f.startswith("resources/") for f in c["files"])
    if FIX.search(c["subj"]) and prod and not AUDIT.search(c["subj"]):
        for f in c["files"]:
            nd = node_of(f)
            if nd:
                esc_by_node.setdefault(nd, set()).add(c["sha"])

gap_nodes = sorted(
    ((k, len(shas)) for k, shas in esc_by_node.items() if not has_granular(k)),
    key=lambda x: (-x[1], x[0]),
)

# ── 4. coverage gaps ────────────────────────────────────────────────────────
untested = sorted(k for k, n in nodes.items() if not n.get("tests") and "waived" not in n)

# ── 5. flaky / repeat-failing checks (needs ≥3 snapshots) ──────────────────
flaps, repeats = [], []
if len(history) >= 3:
    all_checks = sorted({c for h in history for c in h.get("checks", {})})
    for ch in all_checks:
        seq = [h["checks"][ch] for h in history if ch in h.get("checks", {})]
        trans = sum(1 for i in range(1, len(seq)) if (seq[i] == "PASS") != (seq[i - 1] == "PASS"))
        fails = sum(1 for s in seq if s == "FAIL")
        if trans >= 2:
            flaps.append((ch, trans, len(seq)))
        if fails and fails >= max(2, len(seq) // 2):
            repeats.append((ch, fails, len(seq)))

# ── write the reviewable proposals ─────────────────────────────────────────
P = []
def w(s=""):
    P.append(s)

w("# Hermes learn — proposals (review before applying)")
w()
w("> Generated by `scripts/hermes_learn.py`. Deterministic signals → manifest")
w("> improvements. **Nothing is applied automatically** (2026-06-14 decision).")
w("> Run `/hermes-learn` to have a Claude session validate + apply these as a diff.")
w()
w(f"History: {len(history)} ledger snapshot(s), {len(verdicts)} logged verdicts "
  f"({verdicts.count('PASS')} PASS / {verdicts.count('WARN')} WARN / {verdicts.count('FAIL')} FAIL).")
w()

w("## Learn from misses — nodes with escaped bugs but no granular check")
if gap_nodes:
    for k, n in gap_nodes:
        crit = nodes[k].get("criticality", "?")
        w(f"- **{k}** [{nodes[k].get('domain')}/{crit}] — {n} escaped fix(es) touched it, "
          f"but it declares no granular check. *Propose:* add a regression test + a granular check in the manifest.")
else:
    w("- none — every node that had an escaped fix already has a granular check.")
w()

w("## Coverage — untested subsystems")
if untested:
    for k in untested:
        w(f"- **{k}** — no tests in the manifest. *Propose:* add a test, or `waived` with a reason.")
else:
    w("- none — every non-waived subsystem has at least one test.")
w()

w("## Stability — flaky / repeat-failing checks")
if len(history) < 3:
    w(f"- insufficient history ({len(history)} snapshot(s)); need ≥3. Snapshot recorded — re-run after more milestones.")
else:
    if flaps:
        for ch, t, n in flaps:
            w(f"- **{ch}** flapped {t}× over {n} runs. *Propose:* mark flaky / investigate non-determinism.")
    if repeats:
        for ch, fdex, n in repeats:
            w(f"- **{ch}** failed {fdex}/{n} runs. *Propose:* it guards real instability — bump the criticality of its nodes.")
    if not flaps and not repeats:
        w("- none — no check flapped or repeat-failed across the ledger.")
w()

os.makedirs("data", exist_ok=True)
with open("data/hermes_learn_proposals.md", "w") as fh:
    fh.write("\n".join(P) + "\n")

# ── console summary ─────────────────────────────────────────────────────────
n_props = len(gap_nodes) + len(untested) + len(flaps) + len(repeats)
print("Hermes learn (periodic · proposes-only):")
print(f"  ledger: {len(history)} snapshot(s) · verdicts: {len(verdicts)} logged")
print(f"  escaped-bug nodes w/o a guarding check: {len(gap_nodes)}"
      + (f"  → {', '.join(k for k, _ in gap_nodes)}" if gap_nodes else ""))
print(f"  untested subsystems: {len(untested)}" + (f"  → {', '.join(untested)}" if untested else ""))
if len(history) >= 3:
    print(f"  flaky checks: {len(flaps)} · repeat-failing: {len(repeats)}")
else:
    print(f"  stability trends: need ≥3 snapshots (have {len(history)})")
print(f"  {n_props} proposal(s) → data/hermes_learn_proposals.md")
print("  review + apply with /hermes-learn (nothing auto-applied)")
sys.exit(0)
