#!/usr/bin/env bash
# Voiceflow Wrapper Coverage Report
# Generates docs/voiceflow/coverage.md mapping every wrapper method to its
# upstream endpoint by parsing the ensureOk() label immediately after each
# method definition.

set -uo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

OUT="docs/voiceflow/coverage.md"

python3 - "$OUT" <<'PYEOF'
import re
import sys
from pathlib import Path

OUT = Path(sys.argv[1])
REPO = Path('.').resolve()

CLIENTS = [
    ('app/Services/Voiceflow/Client/RuntimeClient.php', 'RuntimeClient', 'general-runtime.voiceflow.com'),
    ('app/Services/Voiceflow/Client/AnalyticsClient.php', 'AnalyticsClient', 'analytics-api.voiceflow.com'),
    ('app/Services/Voiceflow/Client/RealtimeClient.php', 'RealtimeClient', 'realtime-api.voiceflow.com'),
    ('app/Services/Voiceflow/Client/StreamingClient.php', 'StreamingClient', 'general-runtime.voiceflow.com (SSE)'),
]

EXCEPTIONS = [
    ('VoiceflowException', 'abstract base — toLogContext()'),
    ('AuthException', '401 / 403'),
    ('NotFoundException', '404'),
    ('RateLimitedException', '429 (+ retryAfterSeconds)'),
    ('UpstreamException', '5xx / connection failures'),
    ('MisconfiguredException', 'never-sent-the-request'),
]

method_re = re.compile(r'^\s*public function ([a-z][A-Za-z0-9_]*)\s*\(', re.MULTILINE)
ensure_re = re.compile(r"ensureOk\(\$response,\s*'([a-z.]+)'")

def methods_for(path):
    src = Path(path).read_text() if Path(path).is_file() else ''
    rows = []
    matches = list(method_re.finditer(src))
    for i, m in enumerate(matches):
        name = m.group(1)
        # Body = from this method's open paren to the next public function start
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(src)
        body = src[start:end]
        endpoint_match = ensure_re.search(body)
        endpoint = endpoint_match.group(1) if endpoint_match else '(helper)'
        rows.append((name, endpoint))
    return rows

lines = ['---', 'type: reference', 'tags: [voiceflow, coverage, auto-generated]', '---', '', '# Voiceflow Wrapper Coverage', '']
lines.append('Auto-generated by `composer voiceflow:coverage`. Regenerate after adding wrapper methods.')
lines.append('')
total = 0
for path, name, host in CLIENTS:
    rows = methods_for(path)
    total += len(rows)
    lines.append(f'## {name} — `{host}`')
    lines.append('')
    lines.append(f'**{len(rows)} public methods.**')
    lines.append('')
    lines.append('| Method | Endpoint label |')
    lines.append('|---|---|')
    for name_, endpoint in rows:
        lines.append(f'| `{name_}()` | `{endpoint}` |')
    lines.append('')

lines.append(f'## Total wrapped methods: **{total}**')
lines.append('')
lines.append('## Inbound webhooks')
lines.append('')
lines.append('| Route | Controller | Auth |')
lines.append('|---|---|---|')
lines.append('| `POST /api/voiceflow/lead-captured/{agent:slug}` | `VoiceflowWebhookController::leadCaptured` | per-agent `X-Webhook-Secret` |')
lines.append('| `POST /api/voiceflow/webhooks/session/{agent:slug}` | `Voiceflow\\SessionLifecycleController` | per-agent `X-Webhook-Secret` |')
lines.append('')
lines.append('## Exception hierarchy')
lines.append('')
lines.append('| Class | Maps to |')
lines.append('|---|---|')
for cls, note in EXCEPTIONS:
    lines.append(f'| `{cls}` | {note} |')
lines.append('')
lines.append('---')
lines.append('')
lines.append('_Regenerate: `composer voiceflow:coverage`._')

OUT.write_text('\n'.join(lines) + '\n')
print(f'Wrote {OUT}')
PYEOF
