<?php

namespace App\Http\Controllers;

use Inertia\Inertia;
use Inertia\Response;

/**
 * Local-only operator page: the Hermes effectiveness KPIs (git-mined quality
 * trend + regression check, generated by `composer hermes-metrics`). Reads the
 * structured snapshot at data/hermes_metrics.json and renders it with charts;
 * shows an empty state if the report hasn't been generated yet. The route is
 * registered only in the local environment (see routes/web.php), so it never
 * reaches production or the route-smoke test.
 */
class HermesMetricsController extends Controller
{
    public function __invoke(): Response
    {
        $file = base_path('data/hermes_metrics.json');
        $metrics = is_file($file)
            ? json_decode((string) file_get_contents($file), true)
            : null;

        return Inertia::render('Hermes/Metrics', [
            'metrics' => $metrics,
        ]);
    }
}
