<?php

namespace App\Http\Controllers;

use Inertia\Inertia;
use Inertia\Response;

/**
 * Local-only operator page: the Hermes effectiveness KPIs (git-mined quality
 * trend + regression check, generated by `composer hermes-metrics`) plus a LIVE
 * per-run log parsed from the rolling session log (`data/logs/hermes_session.log`,
 * appended every `composer hermes` run). The KPIs are periodic; the run log is
 * always current. Registered only in the local environment (see routes/web.php),
 * so it never reaches production or the route-smoke test.
 */
class HermesMetricsController extends Controller
{
    public function __invoke(): Response
    {
        $file = base_path('data/hermes_metrics.json');
        $metrics = is_file($file)
            ? json_decode((string) file_get_contents($file), true)
            : null;

        [$runs, $ops] = $this->runLog();

        return Inertia::render('Hermes/Metrics', [
            'metrics' => $metrics,
            'runs' => $runs,
            'ops' => $ops,
        ]);
    }

    /**
     * Parse the verdict lines (`<ts> <PASS|WARN|FAIL> p/f/w fast=N dur=Ns`) out
     * of the session log into a per-run history + operational rollup.
     *
     * @return array{0: list<array<string, mixed>>, 1: array<string, mixed>|null}
     */
    private function runLog(): array
    {
        $log = base_path('data/logs/hermes_session.log');
        if (! is_file($log)) {
            return [[], null];
        }

        $runs = [];
        foreach (file($log, FILE_IGNORE_NEW_LINES) ?: [] as $line) {
            if (preg_match('/^(\S+)\s+(PASS|WARN|FAIL)\s+(\d+)\/(\d+)\/(\d+)\s+fast=(\d)(?:\s+dur=(\d+)s)?/', trim($line), $m)) {
                $runs[] = [
                    'ts' => $m[1],
                    'overall' => $m[2],
                    'pass' => (int) $m[3],
                    'fail' => (int) $m[4],
                    'warn' => (int) $m[5],
                    'fast' => $m[6] === '1',
                    'dur' => isset($m[7]) ? (int) $m[7] : null,
                ];
            }
        }

        if ($runs === []) {
            return [[], null];
        }

        $total = count($runs);
        $passes = count(array_filter($runs, static fn ($r) => $r['overall'] === 'PASS'));

        // current consecutive-PASS streak, counted from the most recent run back
        $streak = 0;
        for ($i = $total - 1; $i >= 0; $i--) {
            if ($runs[$i]['overall'] === 'PASS') {
                $streak++;
            } else {
                break;
            }
        }

        $durations = array_values(array_filter(array_column($runs, 'dur'), static fn ($d) => $d !== null));
        $last = $runs[$total - 1];

        $ops = [
            'total' => $total,
            'pass_rate' => (int) round($passes / $total * 100),
            'streak' => $streak,
            'last_ts' => $last['ts'],
            'last_overall' => $last['overall'],
            'last_dur' => $last['dur'],
            'avg_dur' => $durations !== [] ? (int) round(array_sum($durations) / count($durations)) : null,
        ];

        // newest first, capped — this is a log, not the whole history
        $recent = array_reverse(array_slice($runs, -30));

        return [$recent, $ops];
    }
}
